export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCRESE_QUANTITY = "INCRESE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
